#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install apache2 -y
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y
service apache2 restart
apt-get install mysql-server php5-mysql -y
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y
php -m |grep ssh2
service apache2 restart
apt-get install libssh2-1-dev libssh2-php -y
php -m |grep ssh2
service apache2 restart
mysql -h localhost -u root -proot -e "CREATE DATABASE painel"
apt-get install unzip -y
cd /var/www/html
wget https://raw.githubusercontent.com/Alissongithub/openVPN/master/painelovpn.zip
unzip painelovpn.zip
rm painelovpn.zip
clear
echo -e "\033[1;31mPAINEL OPENVPN INSTALADO COM SUCESSO.\033[0m"
